stages:
  - lint
  - test
  - setup
  - build

variables:
  APP_NAME: bwindie-lab
  IMAGE_URL: bwindie
  REGION: us-west-2
  LOB_ACCOUNT_NUMBER: 933741079944

lint:
  image: "gradle:6.8.3-jdk11"
  script: "./gradlew check"
  stage: lint

test:
  image: "gradle:6.8.3-jdk11"
  script: "./gradlew test"
  stage: test

setup_repo:
  tags:
    - standard-msg
  stage: setup
  variables:
    AWS_DEFAULT_REGION: $REGION
  script:
    - |
      if ! aws cloudformation describe-stacks --stack-name ecr-repo-$APP_NAME 2>/dev/null ; then
        aws cloudformation create-stack --stack-name ecr-repo-$APP_NAME \
        --template-body file://_cloudformation/repo.yaml \
        --parameter ParameterKey=ApplicationName,ParameterValue=$APP_NAME
      fi;
    - aws cloudformation wait stack-create-complete --stack-name ecr-repo-$APP_NAME
  only:
    - master
    - develop

build_image:
  tags:
    - standard-msg
  stage: build
  variables:
    AWS_DEFAULT_REGION: $REGION
  script:
    - $(aws ecr get-login --no-include-email)
    - docker build --force-rm --no-cache --pull --tag $IMAGE_URL .
    - docker push $IMAGE_URL